// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransfer {
    #[prost(string, tag="1")]
    pub token_address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub block_number: u64,
    #[prost(string, tag="6")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub log_index: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenTransfers {
    #[prost(message, repeated, tag="1")]
    pub transfers: ::prost::alloc::vec::Vec<TokenTransfer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenActivity {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub transfer_count: u64,
    #[prost(uint64, tag="3")]
    pub last_block: u64,
    #[prost(string, tag="4")]
    pub symbol: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRankings {
    #[prost(message, repeated, tag="1")]
    pub rankings: ::prost::alloc::vec::Vec<TokenActivity>,
    #[prost(uint64, tag="2")]
    pub total_transfers: u64,
    #[prost(uint64, tag="3")]
    pub block_range_start: u64,
    #[prost(uint64, tag="4")]
    pub block_range_end: u64,
}
// @@protoc_insertion_point(module)
